import type { FetchTrialsResponse, NormalizedStudy } from '@/types';

export function generatePdfContent(data: FetchTrialsResponse & { error: false, country_name: string, country_code?: string }) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Clinical Landscape Report - ${data.indication}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          max-width: 1200px;
          margin: 0 auto;
          padding: 40px 20px;
        }
        h1 { color: #0F2044; margin-bottom: 30px; }
        h2 { color: #0D9488; margin-top: 40px; }
        .metrics {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 20px;
          margin: 30px 0;
        }
        .metric-card {
          background: #f8fafc;
          padding: 20px;
          border-radius: 8px;
        }
        .metric-title { font-weight: bold; margin-bottom: 10px; }
        .metric-value { font-size: 24px; }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        th, td {
          text-align: left;
          padding: 12px;
          border-bottom: 1px solid #e2e8f0;
        }
        th { background: #f8fafc; }
      </style>
    </head>
    <body>
      <h1>Clinical Landscape Report</h1>
      
      <p><strong>Indication:</strong> ${data.indication}</p>
      <p><strong>Phase:</strong> ${data.phase}</p>
      <p><strong>Geography:</strong> ${data.country_name}</p>

      <div class="metrics">
        <div class="metric-card">
          <div class="metric-title">Total Trials</div>
          <div class="metric-value">${data.preview.totalTrials}</div>
        </div>
        <div class="metric-card">
          <div class="metric-title">Recruiting Trials</div>
          <div class="metric-value">
            ${data.preview.recruitingTrials}
            <span style="font-size: 16px; color: #64748b">
              (${data.preview.recruitingPct}% recruiting)
            </span>
          </div>
        </div>
        <div class="metric-card">
          <div class="metric-title">Recruitment Competition</div>
          <div class="metric-value">
            ${data.preview.totalTrials <= 3 ? 'LOW' : data.preview.totalTrials <= 10 ? 'MEDIUM' : 'HIGH'}
          </div>
        </div>
      </div>

      <div style="page-break-after: always;"></div>

      <h2>2. Landscape</h2>
      <table>
        <thead>
          <tr>
            <th>NCT ID</th>
            <th>Sponsor</th>
            <th>Phase</th>
            <th>Status</th>
            <th>Countries</th>
          </tr>
        </thead>
        <tbody>
          ${data.studies.slice(0, 10).map((study: NormalizedStudy) => `
            <tr>
              <td>${study.nctId}</td>
              <td>${study.leadSponsorName || 'N/A'}</td>
              <td>${study.phases.join(', ') || 'N/A'}</td>
              <td>${study.overallStatus}</td>
              <td>${study.countries.join(', ')}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div style="page-break-after: always;"></div>

      <h2>3. Distribution</h2>
      <h3 style="margin-top: 20px; margin-bottom: 10px;">Trials by Country</h3>
      <ul>
        ${data.preview.countryDistribution.slice(0, 10).map(c => `
          <li>${c.country}: ${c.count} trials</li>
        `).join('')}
      </ul>

      <h3 style="margin-top: 20px; margin-bottom: 10px;">Trials by Sponsor</h3>
      <ul>
        ${data.preview.topSponsors.slice(0, 10).map(s => `
          <li>${s.sponsor}: ${s.count} trials</li>
        `).join('')}
      </ul>

      <div style="page-break-after: always;"></div>

      <h2>4. Key Insight</h2>
      <p>${data.key_insight || 'No key insight available for this snapshot.'}</p>

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
        <p>Generated by Miterion on ${new Date().toLocaleDateString()}</p>
        <p>Data source: ClinicalTrials.gov</p>
      </div>
    </body>
    </html>
  `;
}