import type { FetchTrialsResponse, NormalizedStudy } from '@/types';

export function generatePdfContent(data: FetchTrialsResponse & { error: false }) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Clinical Landscape Report - ${data.indication}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          max-width: 1200px;
          margin: 0 auto;
          padding: 40px 20px;
        }
        h1 { color: #0F2044; margin-bottom: 30px; }
        h2 { color: #0D9488; margin-top: 40px; }
        .metrics {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 20px;
          margin: 30px 0;
        }
        .metric-card {
          background: #f8fafc;
          padding: 20px;
          border-radius: 8px;
        }
        .metric-title { font-weight: bold; margin-bottom: 10px; }
        .metric-value { font-size: 24px; }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        th, td {
          text-align: left;
          padding: 12px;
          border-bottom: 1px solid #e2e8f0;
        }
        th { background: #f8fafc; }
      </style>
    </head>
    <body>
      <h1>Clinical Landscape Report</h1>
      
      <p><strong>Indication:</strong> ${data.indication}</p>
      <p><strong>Phase:</strong> ${data.phase}</p>
      <p><strong>Geography:</strong> ${data.geo}</p>

      <div class="metrics">
        <div class="metric-card">
          <div class="metric-title">Total Trials</div>
          <div class="metric-value">${data.preview.totalTrials}</div>
        </div>
        <div class="metric-card">
          <div class="metric-title">Recruiting Trials</div>
          <div class="metric-value">
            ${data.preview.recruitingTrials}
            <span style="font-size: 16px; color: #64748b">
              (${data.preview.recruitingPct}%)
            </span>
          </div>
        </div>
      </div>

      <h2>Geographic Distribution</h2>
      <table>
        <thead>
          <tr>
            <th>Country</th>
            <th>Trial Count</th>
          </tr>
        </thead>
        <tbody>
          ${data.preview.countryDistribution.map(c => `
            <tr>
              <td>${c.country}</td>
              <td>${c.count}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>Top Study Sites</h2>
      <table>
        <thead>
          <tr>
            <th>Facility</th>
            <th>Trial Count</th>
          </tr>
        </thead>
        <tbody>
          ${data.preview.topStudySites.map(s => `
            <tr>
              <td>${s.facility}</td>
              <td>${s.count}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>Top Sponsors</h2>
      <table>
        <thead>
          <tr>
            <th>Sponsor</th>
            <th>Trial Count</th>
          </tr>
        </thead>
        <tbody>
          ${data.preview.topSponsors.map(s => `
            <tr>
              <td>${s.sponsor}</td>
              <td>${s.count}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <h2>Trial Details</h2>
      ${data.studies.map((study: NormalizedStudy) => `
        <div style="margin-bottom: 30px; padding-bottom: 20px; border-bottom: 1px solid #e2e8f0;">
          <h3>${study.nctId}</h3>
          <p><strong>Status:</strong> ${study.overallStatus}</p>
          <p><strong>Start Date:</strong> ${study.startDate || 'Not specified'}</p>
          <p><strong>Lead Sponsor:</strong> ${study.leadSponsorName || 'Not specified'}</p>
          <p><strong>Phases:</strong> ${study.phases.join(', ') || 'Not specified'}</p>
          <p><strong>Countries:</strong> ${study.countries.join(', ')}</p>
          
          <h4 style="margin-top: 15px;">Study Sites:</h4>
          <table>
            <thead>
              <tr>
                <th>Facility</th>
                <th>City</th>
                <th>Country</th>
              </tr>
            </thead>
            <tbody>
              ${study.studySites.map(site => `
                <tr>
                  <td>${site.facility}</td>
                  <td>${site.city}</td>
                  <td>${site.country}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>
      `).join('')}

      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b;">
        <p>Generated by Miterion on ${new Date().toLocaleDateString()}</p>
        <p>Data source: ClinicalTrials.gov</p>
      </div>
    </body>
    </html>
  `;
}