import { NextRequest, NextResponse } from "next/server";
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";
import { Resend } from "resend";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export async function POST(req: NextRequest) {
  try {
    const { indication, phase, geography, email, data: previewData } = await req.json();
    const totalTrials = previewData?.preview?.totalTrials || 0;
    const recruitingTrials = previewData?.preview?.recruitingTrials || 0;
    const recruitingPct = previewData?.preview?.recruitingPct || 0;
    const topSponsors = previewData?.preview?.topSponsors || [];
    const countryDistribution = previewData?.preview?.countryDistribution || [];

    const finalScore = Math.max(15, Math.min(95, 100 - (totalTrials * 3)));
    
    const htmlContent = `
      <html>
        <body style="font-family: sans-serif; padding: 40px; color: #333;">
          <h1 style="color: #1a202c;">Miterion Clinical Landscape Snapshot</h1>
          <p><strong>Indication:</strong> ${indication}</p>
          <p><strong>Phase:</strong> ${phase}</p>
          <p><strong>Geography:</strong> ${geography}</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>
          <h2 style="color: #2d3748;">Feasibility Score: ${finalScore} / 100</h2>
          <p>Total active trials: <strong>${totalTrials}</strong></p>
          <p>Recruiting trials: <strong>${recruitingTrials} (${recruitingPct}%)</strong></p>
          <h3 style="color: #4a5568;">Top Sponsors</h3>
          <ul>${topSponsors.slice(0, 5).map((s: any) => `<li>${s.sponsor} - ${s.count} trials</li>`).join('')}</ul>
          <h3 style="color: #4a5568;">Top Countries</h3>
          <ul>${countryDistribution.slice(0, 5).map((c: any) => `<li>${c.country} - ${c.count} trials</li>`).join('')}</ul>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;"/>
          <p><em>Generated by Miterion Platform (Verification: IDENTICAL_BUFFER_V2)</em></p>
        </body>
      </html>
    `;

    let browser;
    try {
      if (process.env.NODE_ENV === "development" || !process.env.VERCEL) {
        const puppeteerLocal = await import("puppeteer");
        browser = await puppeteerLocal.launch({ args: ["--no-sandbox"] });
      } else {
        browser = await puppeteer.launch({ 
          args: chromium.args, 
          executablePath: await chromium.executablePath(), 
          headless: true 
        });
      }
    } catch (err) {
      console.error("Puppeteer launch error:", err);
      return NextResponse.json({ error: "Puppeteer failed to launch" }, { status: 500 });
    }

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle0" as any });
    const pdfBuffer = await page.pdf({ format: "A4" });
    await browser.close();

    console.log("LOG_VERIFY_SIZE:", pdfBuffer.length);

    if (resend && process.env.RESEND_FROM_EMAIL && email) {
      const filename = `snapshot-${indication.replace(/[^a-z0-9]/gi, '_')}.pdf`;
      try {
        console.log(`[generate-pdf] Attempting to send email to ${email} from ${process.env.RESEND_FROM_EMAIL}`);
        const { data: emailData, error: emailError } = await resend.emails.send({
          from: process.env.RESEND_FROM_EMAIL,
          to: email,
          subject: "Your Clinical Trial Snapshot Report",
          html: `<p>Please find your requested Clinical Trial Snapshot for <strong>${indication}</strong> attached.</p>`,
          attachments: [{ filename, content: Buffer.from(pdfBuffer) }],
        });
        
        if (emailError) {
          console.error("[generate-pdf] Resend error:", emailError);
        } else {
          console.log("[generate-pdf] Email sent successfully:", emailData?.id);
        }
      } catch (e) {
        console.error("[generate-pdf] Email exception:", e);
      }
    }

    return new NextResponse(Buffer.from(pdfBuffer), { 
      status: 200, 
      headers: { 
        "Content-Type": "application/pdf", 
        "Content-Disposition": `attachment; filename="snapshot-report.pdf"`,
        "Content-Length": pdfBuffer.length.toString(),
      } 
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "Failed" }, { status: 500 });
  }
}
