import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Cookie Policy | Miterion',
};

export default function CookiesPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-3xl">
      <h1 className="text-4xl font-bold mb-8">Miterion Cookie Policy</h1>
      <p className="text-gray-500 mb-8">Effective Date: March 13, 2026</p>

      <div className="prose max-w-none space-y-6 text-gray-700">
        <p>This Cookie Policy explains how Miterion ("we", "us", or "our") uses cookies and similar technologies to recognize you when you visit our website, miterion.com ("Website"). It explains what these technologies are and why we use them, as well as your rights to control our use of them.</p>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">What are cookies?</h2>
          <p>Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.</p>
          <p className="mt-2">Cookies set by the website owner (in this case, Miterion) are called "first-party cookies". Cookies set by parties other than the website owner are called "third-party cookies". Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">Why do we use cookies?</h2>
          <p>We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons in order for our Website to operate, and we refer to these as "essential" or "strictly necessary" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Website. Third parties serve cookies through our Website for advertising, analytics, and other purposes.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">Types of cookies we use and their purposes:</h2>
          <p>Our Website uses the following types of cookies:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li><strong>Essential / Session Cookies:</strong> These cookies are strictly necessary to provide you with services available through our Website and to use some of its features, such as accessing secure areas. They are temporary and expire when you close your browser. Without these cookies, services like login sessions or maintaining your shopping cart would not be possible. These cookies do not store any personally identifiable information.</li>
            <li><strong>Analytics Cookies (Google Analytics):</strong> These cookies collect information that is used either in aggregate form to help us understand how our Website is being used or how effective our marketing campaigns are, or to help us customize our Website for you. Specifically, our Website uses Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.</li>
            <li><strong>Advertising Cookies (Facebook Pixel):</strong> These cookies are used to make advertising messages more relevant to you and your interests. They perform functions like preventing the same ad from continuously reappearing, ensuring that ads are properly displayed for advertisers, and in some cases, selecting advertisements that are based on your interests. Our Website uses Facebook Pixel, which allows us to measure the effectiveness of our advertising by understanding the actions people take on our Website.</li>
            <li><strong>Third-party Cookies:</strong> In addition to Google Analytics and Facebook Pixel mentioned above, other third-party cookies may be set by external services or content embedded on our site (e.g., embedded videos or social media feeds). These third parties may collect information about your browsing activities across various websites, including ours. We do not have direct control over these cookies or the data they collect.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">User Consent Requirements (Cookie Banner)</h2>
          <p>Upon your first visit to our Website, a cookie consent banner will be displayed, providing you with clear and comprehensive information about the types of cookies we use and their purposes. You will be given the option to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li><strong>Accept All Cookies:</strong> By clicking "Accept All," you consent to the placement of all cookies described in this policy, including essential, analytics, and advertising cookies.</li>
            <li><strong>Manage Preferences/Customize:</strong> This option allows you to select which categories of cookies (e.g., analytics, advertising) you consent to, beyond the strictly necessary cookies which do not require your consent.</li>
            <li><strong>Reject All (or close the banner without action):</strong> If you choose to reject all non-essential cookies or do not make a selection, only essential cookies will be placed on your device.</li>
          </ul>
          <p className="mt-2">Your consent is voluntary and can be withdrawn at any time through our cookie settings or by managing your browser settings as described below. We will record and respect your preferences for a period of up to 12 months, after which we may ask for your consent again.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">Data Retention Periods for Cookies</h2>
          <p>The retention period for cookies varies depending on their purpose:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li><strong>Session Cookies:</strong> These cookies are temporary and are automatically deleted from your device when you close your web browser.</li>
            <li><strong>Persistent Cookies (Analytics and Advertising):</strong> These cookies remain on your device for a longer, predefined period or until you manually delete them.</li>
            <li><strong>Google Analytics:</strong> Most Google Analytics cookies expire between 6 months and 2 years. For example, the `_ga` cookie typically lasts 2 years, and `_gid` lasts 24 hours.</li>
            <li><strong>Facebook Pixel:</strong> Facebook Pixel cookies generally have a lifespan of up to 1 year, though some may expire sooner.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">How can you manage cookies in your browser?</h2>
          <p>You have the right to decide whether to accept or reject cookies. You can exercise your cookie preferences by modifying the settings within your web browser. Each browser offers different methods to manage cookies. You can typically find these settings in the "options" or "preferences" menu of your browser.</p>
          <h3 className="text-xl font-semibold text-navy mt-4 mb-2">Here’s how to manage cookies in popular browsers:</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Google Chrome:</strong> Go to Settings &gt; Privacy and security &gt; Site Settings &gt; Cookies and site data. You can block third-party cookies, clear cookies, or manage exceptions for specific sites.</li>
            <li><strong>Mozilla Firefox:</strong> Go to Options &gt; Privacy &amp; Security &gt; Enhanced Tracking Protection. You can choose between Standard, Strict, or Custom protection.</li>
            <li><strong>Microsoft Edge:</strong> Go to Settings &gt; Privacy, search, and services &gt; Tracking prevention. You can configure tracking prevention levels and clear browsing data.</li>
            <li><strong>Safari (for macOS and iOS):</strong> On macOS: Safari &gt; Preferences &gt; Privacy. On iOS: Settings &gt; Safari &gt; Privacy &amp; Security. You can block all cookies or prevent cross-site tracking.</li>
          </ul>
          <p className="mt-2">Please note that if you choose to set your browser to reject cookies, you may still use our Website, but your access to some functionality and areas of our Website may be restricted or impaired.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">More Information</h2>
          <p>If you have any questions about our use of cookies or other technologies, please contact us at contact@miterion.com.</p>
          <p className="mt-2">This Cookie Policy was last updated on March 13, 2026.</p>
        </section>
      </div>

      <div className="mt-12">
        <Link href="/" className="text-teal hover:underline">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
