import { Metadata } from 'next';
import { Link } from '@/i18n/routing';

export const metadata: Metadata = {
  title: 'Terms of Service | Miterion',
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-3xl">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <p className="text-gray-500 mb-8">Last updated: January 2024</p>

      <div className="prose max-w-none space-y-6 text-gray-700">
        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Miterion&apos;s platform and services, you agree to be
            bound by these Terms of Service. If you do not agree to these terms,
            please do not use our services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">2. Description of Services</h2>
          <p>Miterion provides:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>
              <strong>Clinical Landscape Snapshots</strong> — automated reports generated
              from publicly available ClinicalTrials.gov data.
            </li>
            <li>
              <strong>RFP Harmonization</strong> — professional review and optimization
              of your RFP and site selection documents.
            </li>
            <li>
              <strong>DCT Dashboard (upcoming)</strong> — a dashboard for monitoring
              decentralized clinical trial activity.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">3. Data Sources</h2>
          <p>
            Clinical landscape reports are generated using data from ClinicalTrials.gov,
            a public registry maintained by the U.S. National Library of Medicine.
            Miterion does not guarantee the accuracy or completeness of this data.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">4. Pricing and Payment</h2>
          <p>
            RFP Harmonization services are priced at 1,200–1,800 EUR per engagement
            with a 48-hour turnaround. Pricing is confirmed before work begins.
            Free snapshot reports are provided as a lead generation service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibent text-navy mb-3">5. Intellectual Property</h2>
          <p>
            Reports generated by Miterion are for your internal use only. You may not
            redistribute or resell them without written permission. Uploaded documents
            remain your property; we use them solely to deliver the requested service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">6. Limitation of Liability</h2>
          <p>
            Miterion is not liable for decisions made based on report data. Clinical
            trial data from public registries may be incomplete or outdated. Reports
            are informational tools, not clinical or regulatory advice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-navy mb-3">7. Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href="mailto:contact@miterion.com" className="text-teal hover:underline">
              contact@miterion.com
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12">
        <Link href="/" className="text-teal hover:underline">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
